meta: (( merge ))

networks: (( merge ))

releases:
  - name: dang
    version: latest

jobs:
  - name: nats_z1
    release: dang
    templates:
      - name: nats
        release: dang
    instances: 1
    resource_pool: medium_z1
    networks:
      - name: diego1
        static_ips: (( static_ips(10, 11, 12) ))
    properties:
      nats:
        machines: (( jobs.nats_z1.networks.diego1.static_ips jobs.nats_z2.networks.diego2.static_ips ))
      network_name: diego1

  - name: nats_z2
    release: dang
    templates:
      - name: nats
        release: dang
    instances: 1
    resource_pool: medium_z2
    networks:
      - name: diego2
        static_ips: (( static_ips(10, 11, 12) ))
    properties:
      nats:
        machines: (( jobs.nats_z1.networks.diego1.static_ips jobs.nats_z2.networks.diego2.static_ips ))
      network_name: diego2

  - name: executor_z1
    release: dang
    templates:
      - name: rep
        release: dang
      - name: auctioneer
        release: dang
    instances: 5
    resource_pool: large_z1
    networks:
      - name: diego1
        static_ips: (( static_ips(13, 14, 15, 16, 17) ))
    properties:
      network_name: diego1
      rep:
        nats:
          machines: (( jobs.nats_z1.networks.diego1.static_ips jobs.nats_z2.networks.diego2.static_ips ))
        etcd:
          machines: (( jobs.etcd_z1.networks.diego1.static_ips jobs.etcd_z2.networks.diego2.static_ips jobs.etcd_z3.networks.diego3.static_ips ))
      auctioneer:
        max_concurrent: 100
        etcd:
          machines: (( jobs.etcd_z1.networks.diego1.static_ips jobs.etcd_z2.networks.diego2.static_ips jobs.etcd_z3.networks.diego3.static_ips ))
        nats:
          machines: (( jobs.nats_z1.networks.diego1.static_ips jobs.nats_z2.networks.diego2.static_ips ))

  - name: executor_z2
    release: dang
    templates:
      - name: rep
        release: dang
      - name: auctioneer
        release: dang
    instances: 5
    resource_pool: large_z2
    networks:
      - name: diego2
        static_ips: (( static_ips(13, 14, 15, 16, 17) ))
    properties:
      network_name: diego2
      rep:
        nats:
          machines: (( jobs.nats_z1.networks.diego1.static_ips jobs.nats_z2.networks.diego2.static_ips ))
        etcd:
          machines: (( jobs.etcd_z1.networks.diego1.static_ips jobs.etcd_z2.networks.diego2.static_ips jobs.etcd_z3.networks.diego3.static_ips ))
      auctioneer:
        max_concurrent: 100
        etcd:
          machines: (( jobs.etcd_z1.networks.diego1.static_ips jobs.etcd_z2.networks.diego2.static_ips jobs.etcd_z3.networks.diego3.static_ips ))
        nats:
          machines: (( jobs.nats_z1.networks.diego1.static_ips jobs.nats_z2.networks.diego2.static_ips ))

  - name: etcd_z1
    release: dang
    templates:
      - name: etcd
        release: dang
    instances: 1
    resource_pool: medium_z1
    networks:
      - name: diego1
        static_ips: (( static_ips(18) ))
    properties:
      etcd:
        machines: (( jobs.etcd_z1.networks.diego1.static_ips jobs.etcd_z2.networks.diego2.static_ips jobs.etcd_z3.networks.diego3.static_ips ))
      network_name: diego1

  - name: etcd_z2
    release: dang
    templates:
      - name: etcd
        release: dang
    instances: 0
    resource_pool: medium_z2
    networks:
      - name: diego2
        static_ips: (( static_ips(18) ))
    properties:
      etcd:
        machines: (( jobs.etcd_z1.networks.diego1.static_ips jobs.etcd_z2.networks.diego2.static_ips jobs.etcd_z3.networks.diego3.static_ips ))
      network_name: diego2

  - name: etcd_z3
    release: dang
    templates:
      - name: etcd
        release: dang
    instances: 0
    resource_pool: medium_z3
    networks:
      - name: diego3
        static_ips: (( static_ips(18) ))
    properties:
      etcd:
        machines: (( jobs.etcd_z1.networks.diego1.static_ips jobs.etcd_z2.networks.diego2.static_ips jobs.etcd_z3.networks.diego3.static_ips ))
      network_name: diego3
